import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { FaqList } from "#/components/site/ContentBody";
import { CtaBand, PageHero, SiteShell } from "#/components/site/SiteChrome";
import { TrailerArt } from "#/components/site/TrailerArt";
import { ARTICLES } from "#/content/articles";
import { rangeLabel, TRUCKS } from "#/content/trucks";
import { EQUIPMENT_LABELS, getUseCase } from "#/content/use-cases";
import { breadcrumbLd, faqLd, pageHead } from "#/lib/site";

export const Route = createFileRoute("/use-cases/$slug")({
	loader: ({ params }) => {
		const u = getUseCase(params.slug);
		if (!u) throw notFound();
		return u;
	},
	head: ({ loaderData: u }) => {
		if (!u) return {};
		const path = `/use-cases/${u.slug}`;
		return pageHead({
			title: u.title,
			description: u.description,
			path,
			jsonLd: [
				breadcrumbLd([
					{ name: "Home", path: "/" },
					{ name: "Use cases", path: "/use-cases" },
					{ name: u.name, path },
				]),
				faqLd(u.faqs),
			],
		});
	},
	component: UseCasePage,
});

function UseCasePage() {
	const u = Route.useLoaderData();
	const trucks = TRUCKS.filter((t) => u.trucks.includes(t.slug)).sort(
		(a, b) => u.trucks.indexOf(a.slug) - u.trucks.indexOf(b.slug),
	);
	const articles = ARTICLES.filter((a) => u.articles.includes(a.slug));
	return (
		<SiteShell>
			<PageHero
				crumbs={[
					{ name: "Home", path: "/" },
					{ name: "Use cases", path: "/use-cases" },
					{ name: u.name, path: `/use-cases/${u.slug}` },
				]}
				eyebrow={u.name}
				title={u.title}
				lede={u.intro}
			>
				<Link to="/chat" className="group mt-8 inline-flex items-center gap-2 rounded-sm bg-stone-900 px-5 py-3 text-[14px] font-medium text-stone-50 hover:bg-stone-700">
					Design my {u.name.split(" ")[0].toLowerCase()} trailer
					<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
				</Link>
			</PageHero>

			<section className="mx-auto grid max-w-6xl gap-12 px-4 pb-16 sm:px-6 lg:grid-cols-[1.1fr_0.9fr]">
				<div>
					<h2 className="text-[24px] font-semibold tracking-tight">The layout we build</h2>
					<p className="mt-2 text-[14px] text-stone-500">Generated by our layout engine for this menu on the recommended body.</p>
					<ol className="mt-6 space-y-3">
						{u.zones.map((z, i) => (
							<li key={z} className="flex gap-4 border-b border-stone-200 pb-3 text-[15px] text-stone-800">
								<span className="font-mono text-[12px] text-stone-400">{String(i + 1).padStart(2, "0")}</span>
								{z}
							</li>
						))}
					</ol>
					<h3 className="mt-10 text-[17px] font-semibold">Equipment line</h3>
					<ul className="mt-4 flex flex-wrap gap-2">
						{u.equipment.map((e) => (
							<li key={e} className="rounded-sm border border-stone-200 bg-white px-3 py-1.5 text-[13px] text-stone-700">{EQUIPMENT_LABELS[e] ?? e}</li>
						))}
					</ul>
				</div>
				<aside className="space-y-4">
					{[
						["Power", u.power],
						["Permits", u.permits],
					].map(([t, d]) => (
						<div key={t} className="rounded-sm border border-stone-200 bg-white p-5">
							<h3 className="font-mono text-[11px] uppercase tracking-wider text-stone-500">{t}</h3>
							<p className="mt-2 text-[14.5px] leading-relaxed text-stone-700">{d}</p>
						</div>
					))}
					<div className="rounded-sm bg-[#111110] p-5 text-stone-200">
						<h3 className="font-mono text-[11px] uppercase tracking-wider text-stone-500">Design tips from the build team</h3>
						<ul className="mt-3 space-y-2 text-[14px] leading-relaxed">
							{u.designTips.map((t) => (
								<li key={t} className="flex gap-2.5"><span aria-hidden className="mt-[10px] h-px w-3 shrink-0 bg-stone-500" />{t}</li>
							))}
						</ul>
					</div>
				</aside>
			</section>

			<section className="border-t border-stone-200">
				<div className="mx-auto max-w-6xl px-4 py-16 sm:px-6">
					<h2 className="text-[24px] font-semibold tracking-tight">Recommended trucks</h2>
					<div className="mt-6 grid gap-4 md:grid-cols-3">
						{trucks.map((t, i) => (
							<Link key={t.slug} to="/trucks/$slug" params={{ slug: t.slug }} className="group rounded-sm border border-stone-200 bg-white p-5 hover:border-stone-300">
								<div className="flex h-24 items-end"><TrailerArt vehicleId={t.vehicleId} primary={i === 0 ? "#e8641b" : "#9aa1a8"} className="max-h-24 w-full text-stone-900" /></div>
								<p className="mt-4 text-[16px] font-semibold">{t.name}{i === 0 && <span className="ml-2 rounded-sm bg-[#fbe3cf] px-1.5 py-0.5 align-middle text-[10.5px] font-medium text-[#8a3a0c]">Most common</span>}</p>
								<p className="mt-1 font-mono text-[12.5px] text-stone-500">{rangeLabel(t.planningRange)} planning range</p>
							</Link>
						))}
					</div>
				</div>
			</section>

			<section className="border-t border-stone-200">
				<div className="mx-auto grid max-w-6xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-2">
					<div>
						<h2 className="text-[24px] font-semibold tracking-tight">Questions</h2>
						<div className="mt-6"><FaqList faqs={u.faqs} /></div>
					</div>
					<div>
						<h2 className="text-[24px] font-semibold tracking-tight">Read next</h2>
						<ul className="mt-6 space-y-5">
							{articles.map((a) => (
								<li key={a.slug}>
									<Link to="/resources/$slug" params={{ slug: a.slug }} className="group block">
										<p className="font-mono text-[10.5px] uppercase tracking-wider text-stone-500">{a.category}</p>
										<p className="mt-1 text-[16px] font-medium group-hover:underline group-hover:underline-offset-4">{a.title}</p>
									</Link>
								</li>
							))}
						</ul>
					</div>
				</div>
			</section>
			<CtaBand />
		</SiteShell>
	);
}
