/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as TrucksIndexRouteImport } from './routes/trucks.index'
import { Route as TrucksSlugRouteImport } from './routes/trucks.$slug'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases.index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases.$slug'
import { Route as ApiAgentApproveRouteImport } from './routes/api/agent/approve'
import { Route as ApiAgentChatRouteImport } from './routes/api/agent/chat'
import { Route as ApiAgentDesignRouteImport } from './routes/api/agent/design'
import { Route as ApiAgentFabricationRouteImport } from './routes/api/agent/fabrication'
import { Route as ApiAgentImagesRouteImport } from './routes/api/agent/images'
import { Route as ApiAgentIntakeRouteImport } from './routes/api/agent/intake'
import { Route as ApiAgentLeadsRouteImport } from './routes/api/agent/leads'
import { Route as ApiAgentMenuRouteImport } from './routes/api/agent/menu'
import { Route as ApiAgentPackageRouteImport } from './routes/api/agent/package'
import { Route as ApiAgentPlanRouteImport } from './routes/api/agent/plan'
import { Route as ApiAgentQuizStepRouteImport } from './routes/api/agent/quiz-step'
import { Route as ApiAgentSessionRouteImport } from './routes/api/agent/session'
import { Route as ApiAgentStateRouteImport } from './routes/api/agent/state'
import { Route as ApiAgentSubmissionsRouteImport } from './routes/api/agent/submissions'
import { Route as ApiAgentVideoRouteImport } from './routes/api/agent/video'
import { Route as ApiAssetsFilenameRouteImport } from './routes/api/assets.$filename'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRodinDownloadRouteImport } from './routes/api/rodin/download'
import { Route as ApiRodinProxyDownloadRouteImport } from './routes/api/rodin/proxy-download'
import { Route as ApiRodinStatusRouteImport } from './routes/api/rodin/status'
import { Route as ApiRodinSubmitRouteImport } from './routes/api/rodin/submit'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksIndexRoute = TrucksIndexRouteImport.update({
  id: '/trucks/',
  path: '/trucks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksSlugRoute = TrucksSlugRouteImport.update({
  id: '/trucks/$slug',
  path: '/trucks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/use-cases/',
  path: '/use-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/use-cases/$slug',
  path: '/use-cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentApproveRoute = ApiAgentApproveRouteImport.update({
  id: '/api/agent/approve',
  path: '/api/agent/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentChatRoute = ApiAgentChatRouteImport.update({
  id: '/api/agent/chat',
  path: '/api/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentDesignRoute = ApiAgentDesignRouteImport.update({
  id: '/api/agent/design',
  path: '/api/agent/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentFabricationRoute = ApiAgentFabricationRouteImport.update({
  id: '/api/agent/fabrication',
  path: '/api/agent/fabrication',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentImagesRoute = ApiAgentImagesRouteImport.update({
  id: '/api/agent/images',
  path: '/api/agent/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentIntakeRoute = ApiAgentIntakeRouteImport.update({
  id: '/api/agent/intake',
  path: '/api/agent/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentLeadsRoute = ApiAgentLeadsRouteImport.update({
  id: '/api/agent/leads',
  path: '/api/agent/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMenuRoute = ApiAgentMenuRouteImport.update({
  id: '/api/agent/menu',
  path: '/api/agent/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPackageRoute = ApiAgentPackageRouteImport.update({
  id: '/api/agent/package',
  path: '/api/agent/package',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPlanRoute = ApiAgentPlanRouteImport.update({
  id: '/api/agent/plan',
  path: '/api/agent/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentQuizStepRoute = ApiAgentQuizStepRouteImport.update({
  id: '/api/agent/quiz-step',
  path: '/api/agent/quiz-step',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionRoute = ApiAgentSessionRouteImport.update({
  id: '/api/agent/session',
  path: '/api/agent/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStateRoute = ApiAgentStateRouteImport.update({
  id: '/api/agent/state',
  path: '/api/agent/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSubmissionsRoute = ApiAgentSubmissionsRouteImport.update({
  id: '/api/agent/submissions',
  path: '/api/agent/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentVideoRoute = ApiAgentVideoRouteImport.update({
  id: '/api/agent/video',
  path: '/api/agent/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsFilenameRoute = ApiAssetsFilenameRouteImport.update({
  id: '/api/assets/$filename',
  path: '/api/assets/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRodinDownloadRoute = ApiRodinDownloadRouteImport.update({
  id: '/api/rodin/download',
  path: '/api/rodin/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRodinProxyDownloadRoute = ApiRodinProxyDownloadRouteImport.update({
  id: '/api/rodin/proxy-download',
  path: '/api/rodin/proxy-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRodinStatusRoute = ApiRodinStatusRouteImport.update({
  id: '/api/rodin/status',
  path: '/api/rodin/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRodinSubmitRoute = ApiRodinSubmitRouteImport.update({
  id: '/api/rodin/submit',
  path: '/api/rodin/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/trucks/$slug': typeof TrucksSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/trucks/': typeof TrucksIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/api/agent/approve': typeof ApiAgentApproveRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/design': typeof ApiAgentDesignRoute
  '/api/agent/fabrication': typeof ApiAgentFabricationRoute
  '/api/agent/images': typeof ApiAgentImagesRoute
  '/api/agent/intake': typeof ApiAgentIntakeRoute
  '/api/agent/leads': typeof ApiAgentLeadsRoute
  '/api/agent/menu': typeof ApiAgentMenuRoute
  '/api/agent/package': typeof ApiAgentPackageRoute
  '/api/agent/plan': typeof ApiAgentPlanRoute
  '/api/agent/quiz-step': typeof ApiAgentQuizStepRoute
  '/api/agent/session': typeof ApiAgentSessionRoute
  '/api/agent/state': typeof ApiAgentStateRoute
  '/api/agent/submissions': typeof ApiAgentSubmissionsRoute
  '/api/agent/video': typeof ApiAgentVideoRoute
  '/api/assets/$filename': typeof ApiAssetsFilenameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rodin/download': typeof ApiRodinDownloadRoute
  '/api/rodin/proxy-download': typeof ApiRodinProxyDownloadRoute
  '/api/rodin/status': typeof ApiRodinStatusRoute
  '/api/rodin/submit': typeof ApiRodinSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/trucks/$slug': typeof TrucksSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/resources': typeof ResourcesIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/trucks': typeof TrucksIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/api/agent/approve': typeof ApiAgentApproveRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/design': typeof ApiAgentDesignRoute
  '/api/agent/fabrication': typeof ApiAgentFabricationRoute
  '/api/agent/images': typeof ApiAgentImagesRoute
  '/api/agent/intake': typeof ApiAgentIntakeRoute
  '/api/agent/leads': typeof ApiAgentLeadsRoute
  '/api/agent/menu': typeof ApiAgentMenuRoute
  '/api/agent/package': typeof ApiAgentPackageRoute
  '/api/agent/plan': typeof ApiAgentPlanRoute
  '/api/agent/quiz-step': typeof ApiAgentQuizStepRoute
  '/api/agent/session': typeof ApiAgentSessionRoute
  '/api/agent/state': typeof ApiAgentStateRoute
  '/api/agent/submissions': typeof ApiAgentSubmissionsRoute
  '/api/agent/video': typeof ApiAgentVideoRoute
  '/api/assets/$filename': typeof ApiAssetsFilenameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rodin/download': typeof ApiRodinDownloadRoute
  '/api/rodin/proxy-download': typeof ApiRodinProxyDownloadRoute
  '/api/rodin/status': typeof ApiRodinStatusRoute
  '/api/rodin/submit': typeof ApiRodinSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/trucks/$slug': typeof TrucksSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/trucks/': typeof TrucksIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/api/agent/approve': typeof ApiAgentApproveRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/design': typeof ApiAgentDesignRoute
  '/api/agent/fabrication': typeof ApiAgentFabricationRoute
  '/api/agent/images': typeof ApiAgentImagesRoute
  '/api/agent/intake': typeof ApiAgentIntakeRoute
  '/api/agent/leads': typeof ApiAgentLeadsRoute
  '/api/agent/menu': typeof ApiAgentMenuRoute
  '/api/agent/package': typeof ApiAgentPackageRoute
  '/api/agent/plan': typeof ApiAgentPlanRoute
  '/api/agent/quiz-step': typeof ApiAgentQuizStepRoute
  '/api/agent/session': typeof ApiAgentSessionRoute
  '/api/agent/state': typeof ApiAgentStateRoute
  '/api/agent/submissions': typeof ApiAgentSubmissionsRoute
  '/api/agent/video': typeof ApiAgentVideoRoute
  '/api/assets/$filename': typeof ApiAssetsFilenameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rodin/download': typeof ApiRodinDownloadRoute
  '/api/rodin/proxy-download': typeof ApiRodinProxyDownloadRoute
  '/api/rodin/status': typeof ApiRodinStatusRoute
  '/api/rodin/submit': typeof ApiRodinSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/faq'
    | '/how-it-works'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/pricing'
    | '/report'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/resources/$slug'
    | '/stories/$slug'
    | '/trucks/$slug'
    | '/use-cases/$slug'
    | '/resources/'
    | '/stories/'
    | '/trucks/'
    | '/use-cases/'
    | '/api/agent/approve'
    | '/api/agent/chat'
    | '/api/agent/design'
    | '/api/agent/fabrication'
    | '/api/agent/images'
    | '/api/agent/intake'
    | '/api/agent/leads'
    | '/api/agent/menu'
    | '/api/agent/package'
    | '/api/agent/plan'
    | '/api/agent/quiz-step'
    | '/api/agent/session'
    | '/api/agent/state'
    | '/api/agent/submissions'
    | '/api/agent/video'
    | '/api/assets/$filename'
    | '/api/auth/$'
    | '/api/rodin/download'
    | '/api/rodin/proxy-download'
    | '/api/rodin/status'
    | '/api/rodin/submit'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/faq'
    | '/how-it-works'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/pricing'
    | '/report'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/resources/$slug'
    | '/stories/$slug'
    | '/trucks/$slug'
    | '/use-cases/$slug'
    | '/resources'
    | '/stories'
    | '/trucks'
    | '/use-cases'
    | '/api/agent/approve'
    | '/api/agent/chat'
    | '/api/agent/design'
    | '/api/agent/fabrication'
    | '/api/agent/images'
    | '/api/agent/intake'
    | '/api/agent/leads'
    | '/api/agent/menu'
    | '/api/agent/package'
    | '/api/agent/plan'
    | '/api/agent/quiz-step'
    | '/api/agent/session'
    | '/api/agent/state'
    | '/api/agent/submissions'
    | '/api/agent/video'
    | '/api/assets/$filename'
    | '/api/auth/$'
    | '/api/rodin/download'
    | '/api/rodin/proxy-download'
    | '/api/rodin/status'
    | '/api/rodin/submit'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/faq'
    | '/how-it-works'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/pricing'
    | '/report'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/resources/$slug'
    | '/stories/$slug'
    | '/trucks/$slug'
    | '/use-cases/$slug'
    | '/resources/'
    | '/stories/'
    | '/trucks/'
    | '/use-cases/'
    | '/api/agent/approve'
    | '/api/agent/chat'
    | '/api/agent/design'
    | '/api/agent/fabrication'
    | '/api/agent/images'
    | '/api/agent/intake'
    | '/api/agent/leads'
    | '/api/agent/menu'
    | '/api/agent/package'
    | '/api/agent/plan'
    | '/api/agent/quiz-step'
    | '/api/agent/session'
    | '/api/agent/state'
    | '/api/agent/submissions'
    | '/api/agent/video'
    | '/api/assets/$filename'
    | '/api/auth/$'
    | '/api/rodin/download'
    | '/api/rodin/proxy-download'
    | '/api/rodin/status'
    | '/api/rodin/submit'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PricingRoute: typeof PricingRoute
  ReportRoute: typeof ReportRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  TrucksSlugRoute: typeof TrucksSlugRoute
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  TrucksIndexRoute: typeof TrucksIndexRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
  ApiAgentApproveRoute: typeof ApiAgentApproveRoute
  ApiAgentChatRoute: typeof ApiAgentChatRoute
  ApiAgentDesignRoute: typeof ApiAgentDesignRoute
  ApiAgentFabricationRoute: typeof ApiAgentFabricationRoute
  ApiAgentImagesRoute: typeof ApiAgentImagesRoute
  ApiAgentIntakeRoute: typeof ApiAgentIntakeRoute
  ApiAgentLeadsRoute: typeof ApiAgentLeadsRoute
  ApiAgentMenuRoute: typeof ApiAgentMenuRoute
  ApiAgentPackageRoute: typeof ApiAgentPackageRoute
  ApiAgentPlanRoute: typeof ApiAgentPlanRoute
  ApiAgentQuizStepRoute: typeof ApiAgentQuizStepRoute
  ApiAgentSessionRoute: typeof ApiAgentSessionRoute
  ApiAgentStateRoute: typeof ApiAgentStateRoute
  ApiAgentSubmissionsRoute: typeof ApiAgentSubmissionsRoute
  ApiAgentVideoRoute: typeof ApiAgentVideoRoute
  ApiAssetsFilenameRoute: typeof ApiAssetsFilenameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRodinDownloadRoute: typeof ApiRodinDownloadRoute
  ApiRodinProxyDownloadRoute: typeof ApiRodinProxyDownloadRoute
  ApiRodinStatusRoute: typeof ApiRodinStatusRoute
  ApiRodinSubmitRoute: typeof ApiRodinSubmitRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/': {
      id: '/trucks/'
      path: '/trucks'
      fullPath: '/trucks/'
      preLoaderRoute: typeof TrucksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/$slug': {
      id: '/trucks/$slug'
      path: '/trucks/$slug'
      fullPath: '/trucks/$slug'
      preLoaderRoute: typeof TrucksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/use-cases'
      fullPath: '/use-cases/'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/use-cases/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/approve': {
      id: '/api/agent/approve'
      path: '/api/agent/approve'
      fullPath: '/api/agent/approve'
      preLoaderRoute: typeof ApiAgentApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/chat': {
      id: '/api/agent/chat'
      path: '/api/agent/chat'
      fullPath: '/api/agent/chat'
      preLoaderRoute: typeof ApiAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/design': {
      id: '/api/agent/design'
      path: '/api/agent/design'
      fullPath: '/api/agent/design'
      preLoaderRoute: typeof ApiAgentDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/fabrication': {
      id: '/api/agent/fabrication'
      path: '/api/agent/fabrication'
      fullPath: '/api/agent/fabrication'
      preLoaderRoute: typeof ApiAgentFabricationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/images': {
      id: '/api/agent/images'
      path: '/api/agent/images'
      fullPath: '/api/agent/images'
      preLoaderRoute: typeof ApiAgentImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/intake': {
      id: '/api/agent/intake'
      path: '/api/agent/intake'
      fullPath: '/api/agent/intake'
      preLoaderRoute: typeof ApiAgentIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/leads': {
      id: '/api/agent/leads'
      path: '/api/agent/leads'
      fullPath: '/api/agent/leads'
      preLoaderRoute: typeof ApiAgentLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/menu': {
      id: '/api/agent/menu'
      path: '/api/agent/menu'
      fullPath: '/api/agent/menu'
      preLoaderRoute: typeof ApiAgentMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/package': {
      id: '/api/agent/package'
      path: '/api/agent/package'
      fullPath: '/api/agent/package'
      preLoaderRoute: typeof ApiAgentPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/plan': {
      id: '/api/agent/plan'
      path: '/api/agent/plan'
      fullPath: '/api/agent/plan'
      preLoaderRoute: typeof ApiAgentPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/quiz-step': {
      id: '/api/agent/quiz-step'
      path: '/api/agent/quiz-step'
      fullPath: '/api/agent/quiz-step'
      preLoaderRoute: typeof ApiAgentQuizStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/session': {
      id: '/api/agent/session'
      path: '/api/agent/session'
      fullPath: '/api/agent/session'
      preLoaderRoute: typeof ApiAgentSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/state': {
      id: '/api/agent/state'
      path: '/api/agent/state'
      fullPath: '/api/agent/state'
      preLoaderRoute: typeof ApiAgentStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/submissions': {
      id: '/api/agent/submissions'
      path: '/api/agent/submissions'
      fullPath: '/api/agent/submissions'
      preLoaderRoute: typeof ApiAgentSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/video': {
      id: '/api/agent/video'
      path: '/api/agent/video'
      fullPath: '/api/agent/video'
      preLoaderRoute: typeof ApiAgentVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$filename': {
      id: '/api/assets/$filename'
      path: '/api/assets/$filename'
      fullPath: '/api/assets/$filename'
      preLoaderRoute: typeof ApiAssetsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rodin/download': {
      id: '/api/rodin/download'
      path: '/api/rodin/download'
      fullPath: '/api/rodin/download'
      preLoaderRoute: typeof ApiRodinDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rodin/proxy-download': {
      id: '/api/rodin/proxy-download'
      path: '/api/rodin/proxy-download'
      fullPath: '/api/rodin/proxy-download'
      preLoaderRoute: typeof ApiRodinProxyDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rodin/status': {
      id: '/api/rodin/status'
      path: '/api/rodin/status'
      fullPath: '/api/rodin/status'
      preLoaderRoute: typeof ApiRodinStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rodin/submit': {
      id: '/api/rodin/submit'
      path: '/api/rodin/submit'
      fullPath: '/api/rodin/submit'
      preLoaderRoute: typeof ApiRodinSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PricingRoute: PricingRoute,
  ReportRoute: ReportRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  TrucksSlugRoute: TrucksSlugRoute,
  UseCasesSlugRoute: UseCasesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  TrucksIndexRoute: TrucksIndexRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
  ApiAgentApproveRoute: ApiAgentApproveRoute,
  ApiAgentChatRoute: ApiAgentChatRoute,
  ApiAgentDesignRoute: ApiAgentDesignRoute,
  ApiAgentFabricationRoute: ApiAgentFabricationRoute,
  ApiAgentImagesRoute: ApiAgentImagesRoute,
  ApiAgentIntakeRoute: ApiAgentIntakeRoute,
  ApiAgentLeadsRoute: ApiAgentLeadsRoute,
  ApiAgentMenuRoute: ApiAgentMenuRoute,
  ApiAgentPackageRoute: ApiAgentPackageRoute,
  ApiAgentPlanRoute: ApiAgentPlanRoute,
  ApiAgentQuizStepRoute: ApiAgentQuizStepRoute,
  ApiAgentSessionRoute: ApiAgentSessionRoute,
  ApiAgentStateRoute: ApiAgentStateRoute,
  ApiAgentSubmissionsRoute: ApiAgentSubmissionsRoute,
  ApiAgentVideoRoute: ApiAgentVideoRoute,
  ApiAssetsFilenameRoute: ApiAssetsFilenameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRodinDownloadRoute: ApiRodinDownloadRoute,
  ApiRodinProxyDownloadRoute: ApiRodinProxyDownloadRoute,
  ApiRodinStatusRoute: ApiRodinStatusRoute,
  ApiRodinSubmitRoute: ApiRodinSubmitRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
