/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiRodinSubmitRouteImport } from './routes/api/rodin/submit'
import { Route as ApiRodinStatusRouteImport } from './routes/api/rodin/status'
import { Route as ApiRodinProxyDownloadRouteImport } from './routes/api/rodin/proxy-download'
import { Route as ApiRodinDownloadRouteImport } from './routes/api/rodin/download'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRodinSubmitRoute = ApiRodinSubmitRouteImport.update({
  id: '/api/rodin/submit',
  path: '/api/rodin/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRodinStatusRoute = ApiRodinStatusRouteImport.update({
  id: '/api/rodin/status',
  path: '/api/rodin/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRodinProxyDownloadRoute = ApiRodinProxyDownloadRouteImport.update({
  id: '/api/rodin/proxy-download',
  path: '/api/rodin/proxy-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRodinDownloadRoute = ApiRodinDownloadRouteImport.update({
  id: '/api/rodin/download',
  path: '/api/rodin/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rodin/download': typeof ApiRodinDownloadRoute
  '/api/rodin/proxy-download': typeof ApiRodinProxyDownloadRoute
  '/api/rodin/status': typeof ApiRodinStatusRoute
  '/api/rodin/submit': typeof ApiRodinSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rodin/download': typeof ApiRodinDownloadRoute
  '/api/rodin/proxy-download': typeof ApiRodinProxyDownloadRoute
  '/api/rodin/status': typeof ApiRodinStatusRoute
  '/api/rodin/submit': typeof ApiRodinSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rodin/download': typeof ApiRodinDownloadRoute
  '/api/rodin/proxy-download': typeof ApiRodinProxyDownloadRoute
  '/api/rodin/status': typeof ApiRodinStatusRoute
  '/api/rodin/submit': typeof ApiRodinSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/api/auth/$'
    | '/api/rodin/download'
    | '/api/rodin/proxy-download'
    | '/api/rodin/status'
    | '/api/rodin/submit'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio'
    | '/api/auth/$'
    | '/api/rodin/download'
    | '/api/rodin/proxy-download'
    | '/api/rodin/status'
    | '/api/rodin/submit'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/api/auth/$'
    | '/api/rodin/download'
    | '/api/rodin/proxy-download'
    | '/api/rodin/status'
    | '/api/rodin/submit'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRodinDownloadRoute: typeof ApiRodinDownloadRoute
  ApiRodinProxyDownloadRoute: typeof ApiRodinProxyDownloadRoute
  ApiRodinStatusRoute: typeof ApiRodinStatusRoute
  ApiRodinSubmitRoute: typeof ApiRodinSubmitRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rodin/submit': {
      id: '/api/rodin/submit'
      path: '/api/rodin/submit'
      fullPath: '/api/rodin/submit'
      preLoaderRoute: typeof ApiRodinSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rodin/status': {
      id: '/api/rodin/status'
      path: '/api/rodin/status'
      fullPath: '/api/rodin/status'
      preLoaderRoute: typeof ApiRodinStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rodin/proxy-download': {
      id: '/api/rodin/proxy-download'
      path: '/api/rodin/proxy-download'
      fullPath: '/api/rodin/proxy-download'
      preLoaderRoute: typeof ApiRodinProxyDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rodin/download': {
      id: '/api/rodin/download'
      path: '/api/rodin/download'
      fullPath: '/api/rodin/download'
      preLoaderRoute: typeof ApiRodinDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRodinDownloadRoute: ApiRodinDownloadRoute,
  ApiRodinProxyDownloadRoute: ApiRodinProxyDownloadRoute,
  ApiRodinStatusRoute: ApiRodinStatusRoute,
  ApiRodinSubmitRoute: ApiRodinSubmitRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
